### ISSUE TITLE
New build v2.0.9

### ISSUE THREAD

**Issue by j-kapp** [conda-forge/geoserver-restconfig-feedstock#2]
### Comment:

Hi there!

I'm not really sure where to post this or if this is the correct format, but could someone (@swainn ?) please make a new conda build of the geoserver-restconfig package. v2.0.8 is incompatible with urllib3 > 2.0 due to the renaming of the 'method_whitelist' parameter to 'allowed_methods'. The workaround at the moment is just to specify 'urllib3<2.0' when making a new environment, but it would be nice not to have to do this going forward.

Thank you.

**Comment by swainn** [comment]
Hi @j-kapp this is the right place. I'll add the restriction to the requirements and prepare a new build.

**Comment by swainn** [comment]
I've added pull request #4 to address this. This will build a new version of 2.0.8 with the fix.

**Comment by j-kapp** [comment]
Thank you @swainn. It's working for me now without the workaround
